{% set data = load_setup_py_data() %}

package:
  name: wsp-matrix-butler
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: auto
  noarch: python

requirements:
  host:
    - python
  run:
    - python
    - pandas >=0.16
    - numpy >=1.14

about:
  home: https://github.com/wsp-sag/wsp-matrix-butler
  license: MIT
  license_file: LICENSE
  summary: A SQLite-based mini-file system for organizing binary files for the Greater Golden Horseshoe Model.

extra:
  maintainers:
    - Brian Cheung
    - Peter Kucirek
