{% set data = load_setup_py_data() %}

package:
  name: wsp-matrix-butler
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python setup.py --quiet install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
  run:
    - python >=3.7
    - pandas >=0.24
    - numpy

about:
  home: https://github.com/wsp-sag/wsp-matrix-butler
  license: MIT
  license_file: LICENSE
  summary: A SQLite-based mini-file system for organizing binary files for the Greater Golden Horseshoe Model.

extra:
  maintainers:
    - Brian Cheung
